#!/bin/sh

# This script is part of the hexagonrpcd service.
# The service is is triggered by udev when a /dev/fastrpc-* device appears,
# and will check whether adsp or cdsp is to be used for hexagonrpcd.
# If the correct device in /dev/ exists, it will start hexagonrpcd.

SDSP_FOUND=0
ADSP_FOUND=0

for remoteproc in /sys/class/remoteproc/remoteproc*; do
    # If no matches are found, $remoteproc literally includes the wildcard
    if ! [ -e "$remoteproc" ]; then continue; fi;

    name=$(cat "$remoteproc"/name)

    if [ "$name" = "adsp" ]; then
        ADSP_FOUND=1
    elif [ "$name" = "sdsp" ]; then
        SDSP_FOUND=1
    fi
done

if [ "$SDSP_FOUND" = "1" ] && [ -e "/dev/fastrpc-sdsp" ]; then
    echo "Starting hexagonrpcd with sdsp"

    exec /usr/bin/hexagonrpcd -f /dev/fastrpc-sdsp -d sdsp -s
elif [ "$SDSP_FOUND" = "0" ] && [ "$ADSP_FOUND" = "1" ] && [ -e "/dev/fastrpc-adsp" ]; then
    echo "Starting hexagonrpcd with adsp"

    exec /usr/bin/hexagonrpcd -f /dev/fastrpc-adsp -d adsp -s
fi

exit 0
